# Generated by Django 4.1.4 on 2022-12-16 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('comp', models.CharField(max_length=20)),
                ('usr', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('updated_at', models.TimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grpname', models.CharField(max_length=20)),
                ('sequence', models.CharField(max_length=1)),
                ('inactive', models.BooleanField()),
                ('note', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuname', models.CharField(max_length=20)),
                ('taskname', models.CharField(max_length=20)),
                ('groupname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.menugroup')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('pyname', models.CharField(max_length=30)),
                ('inactivetask', models.BooleanField()),
                ('notetask', models.CharField(max_length=50)),
                ('lastupdatedate', models.DateField(auto_now=True)),
                ('lastupdatetime', models.TimeField(auto_now=True)),
                ('lastupdatetask', models.CharField(max_length=50)),
                ('lastupdateip', models.CharField(max_length=20)),
                ('lastupdateuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.menumaster')),
            ],
        ),
    ]
