# Generated by Django 4.1.4 on 2022-12-19 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pynameacc', models.CharField(max_length=30)),
                ('inactivetaskacc', models.BooleanField()),
                ('notetaskacc', models.CharField(max_length=50)),
                ('viewaccess', models.BooleanField()),
                ('addaccess', models.BooleanField()),
                ('editaccess', models.BooleanField()),
                ('deleteaccess', models.BooleanField()),
                ('inactiveaccess', models.BooleanField()),
                ('lastupdateuseracc', models.CharField(max_length=50)),
                ('lastupdatedateacc', models.DateField()),
                ('lastupdatetimeacc', models.TimeField()),
                ('lastupdatetaskacc', models.CharField(max_length=50)),
                ('lastupdateipacc', models.CharField(max_length=20)),
                ('taskacc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.menumaster')),
                ('taskuseracc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
