# Generated by Django 4.1.4 on 2022-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usertaskaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskaccess',
            name='lastupdatedateacc',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usertaskaccess',
            name='lastupdatetimeacc',
            field=models.TimeField(auto_now=True),
        ),
    ]
